# Generated by Django 2.2.13 on 2020-06-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_1',
            new_name='category_l',
        ),
    ]
